export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const RESET_AUTHED_USER = 'REST_AUTHED_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_USER_TO_QUESTION = 'SET_USER_TO_QUESTION';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
