export const SET_AUTH_USER = 'SET_AUTH_USER';
export const RESET_AUTH_USER = 'REST_AUTH_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_USER_TO_QUESTION = 'SET_USER_TO_QUESTION';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const REGISTER_USER = 'REGISTER_USER';
