export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const RESET_AUTHED_USER = 'REST_AUTHED_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_USER_QUESTION = 'SET_USER_QUESTION';
export const SET_USER_ANSWER = 'SET_USER_ANSWER';
